
				[package]
				name = "node-template-runtime-wasm"
				version = "1.0.0"
				edition = "2018"

				[lib]
				name = "node_template_runtime"
				crate-type = ["cdylib"]

				[dependencies]
				wasm_project = { package = "node-template-runtime", path = "/Users/drewstone/code/commonwealth/pure-zk/runtime", default-features = false }
			