[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"
license = "Unlicense"

[[bin]]
name = "node-template"
path = "src/main.rs"

[dependencies]
futures = "0.3.1"
log = "0.4.8"
sc-cli = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-executor = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sc-service = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-network = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-aura = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
grandpa = { version = "0.8", package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate.git" }
grandpa-primitives = { version = "2.0.0", package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate.git" }
sc-client = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git" }
structopt = "0.3.8"

node-template-runtime = { version = "2.0.0", path = "./runtime" }

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { version = "2.0.0", package = "substrate-build-script-utils", git = "https://github.com/paritytech/substrate.git" }
