[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
build = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2018"
homepage = "https://substrate.dev"
license = "Unlicense"
name = "node-template"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
structopt = "0.3.8"

sc-cli = { version = "0.8.0", features = ["wasmtime"] }
sp-core = { version = "2.0.0" }
sc-executor = { version = "0.8.0", features = ["wasmtime"] }
sc-service = { version = "0.8.0", features = ["wasmtime"] }
sc-telemetry = { version = "2.0.0" }
sc-keystore = { version = "2.0.0" }
sp-inherents = { version = "2.0.0" }
sc-transaction-pool = { version = "2.0.0" }
sp-transaction-pool = { version = "2.0.0" }
sc-consensus-aura = { version = "0.8.0" }
sp-consensus-aura = { version = "0.8.0" }
sp-consensus = { version = "0.8.0" }
sc-consensus = { version = "0.8.0" }
sc-finality-grandpa = { version = "0.8.0" }
sp-finality-grandpa = { version = "2.0.0" }
sc-client-api = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { version = "2.0.0" }
sp-api = { version = "2.0.0" }
sc-rpc-api = { version = "0.8.0" }
sp-blockchain = { version = "2.0.0" }
sp-block-builder = { version = "2.0.0" }
sc-basic-authorship = { version = "0.8.0" }
substrate-frame-rpc-system = { version = "2.0.0" }
pallet-transaction-payment-rpc = { version = "2.0.0" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "2.0.0" }
frame-benchmarking-cli = { version = "2.0.0" }

node-template-runtime = { version = "2.0.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0" }

[features]
default = []
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
]